name: Deploy

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2
            - name: Login via SSH
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.IP_ADDRESS }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
                script: |
                    mkdir tiktofiy
                    git fetch https://github.com/salvia-dev/tiktofiy.git
                    yarn install
                    yarn build
                    pm2 delete all
                    pm2 start yarn --name @tiktofiy/api -- api:start
                    pm2 start yarn --name @tiktofiy/client -- client:start
