name: Deploy

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2
            - name: Login via SSH Key
              uses: webfactory/ssh-agent@v0.5.4
              with:
                ssh-private-key: ${{ secrets.SSH_KEY }}
            
            - run: git clone https://github.com/salvia-dev/tiktofiy.git
            - run: cd tiktofiy
            - run: yarn install
            - run: yarn build
            - run: pm2 delete all
            - run: pm2 start yarn --name @tiktofiy/api -- api:start
            - run: pm2 start yarn --name @tiktofiy/client -- client:start
